[[main]]
  name = "Docs"
  pageRef = "docs"
  weight = 10

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Thought"
  pageRef = "thought"
  weight = 25

[[main]]
  name = "Archive"
  pageRef = "archive"
  weight = 30
